query:
  proj_dir: /home/marvin/ETH_Study/3DV/3DV/outputs/aachen_sub2/query_sequences_v2/21
  retrieval_conf: "netvlad"
  feature_conf: "superpoint_aachen"
  matcher_conf: "superglue"
  local_visual: True
database:
  proj_dir: /home/marvin/ETH_Study/3DV/3DV/outputs/aachen_sub2/outputs
ground_truth: /home/marvin/ETH_Study/3DV/3DV/outputs/aachen_exp/ref/outputs
reconstruction:
  num_match_pairs: 20
point_cloud_registration:
  min_percentage: 0.6
  min_num_2d_pts: 4
