query:
  proj_dir: /home/marvin/ETH_Study/3DV/3DV/outputs/aachen_sub/query/2
  retrieval_conf: "netvlad"
  feature_conf: "superpoint_aachen"
  matcher_conf: "superglue"
  local_visual: True
database:
  proj_dir: /home/marvin/ETH_Study/3DV/3DV/outputs/aachen_exp/ref/outputs/