query:
  proj_dir: /home/liyzhu/ETHZ/3DV/outputs/query_sequencies/7
  retrieval_conf: "netvlad"
  feature_conf: "superpoint_aachen"
  matcher_conf: "superglue"
  local_visual: False
database:
  proj_dir: /home/liyzhu/ETHZ/3DV/outputs/superpoint+superglue_aachen