query:
  proj_dir: /cluster/project/infk/courses/252-0579-00L/group16/PCR/Aachen_sub/query_sequences_v2
query_params:
  retrieval_conf: "netvlad"
  feature_conf: "superpoint_aachen"
  matcher_conf: "superglue"
  local_visual: False
database:
  proj_dir: /cluster/project/infk/courses/252-0579-00L/group16/PCR/Aachen_sub/new_triangulation/outputs
reconstruction:
  num_match_pairs: 20
point_cloud_registration:
  min_percentage: 0.6
  min_num_2d_pts: 4
  proj_dir: /cluster/project/infk/courses/252-0579-00L/group16/PCR/Aachen_sub/new_triangulation/outputs